---
- hosts: all
  become: true  # you need sudo

  tasks:
  - name: package update (apt)
    apt: update_cache=yes cache_valid_time=3600

  - name: Install nginx 
    action: apt pkg=nginx state=present

  - name: Copy nginx config file to /etc/nginx/nginx.conf
    copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

# TO PLACE playbooks/files/welcome_page.html AS A SPECIAL DEFAULT WELCOME PAGE 
  - name: Copy nginx specific welcome page to be shown in default site
    copy: src=files/welcome_page.html dest=/var/www/html/index.nginx-debian.html

#  - name: Remove nginx default site
#    file: >
#      dest=/etc/nginx/sites-available/default
#      state=absent

# TO BE USED AS A PROXY TO REDIRECT EXTERNAL TRAFFIC
#  - name: Copy nginx vhost config file for proxypass
#    copy: src=files/proxypass.conf dest=/etc/nginx/sites-available/proxypass.conf

#  - name: Enable configuration for proxypass
#    file: >
#      dest=/etc/nginx/sites-enabled/proxypass.conf
#      src=/etc/nginx/sites-available/proxypass.conf
#      state=link

# TO BE USED AS A REVERSE PROXY FOR AN APPLICATION
#   - name: Copy nginx vhost config file for myapp
#     copy: src=files/myapp.conf dest=/etc/nginx/sites-available/myapp.conf

#   - name: Enable configuration for myapp
#     file: >
#       dest=/etc/nginx/sites-enabled/myapp.conf
#       src=/etc/nginx/sites-available/myapp.conf
#       state=link

  - name: Restart nginx
    service: name=nginx state=restarted
